### ISSUE TITLE
Issue with a workload execution

### ISSUE THREAD

**Issue by denissb** [morten-olsen/mini-loader#44]
**Describe the bug**

There is an issue when running workloads with auto-imports, see error:
```
✖ Creating load 0
TRPCClientError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
    at Function.from (file:///Users/denissb/.nvm/versions/node/v20.10.0/lib/node_modules/@morten-olsen/mini-loader-cli/node_modules/@trpc/client/dist/TRPCClientError-38f9a32a.mjs:27:20)
    at file:///Users/denissb/.nvm/versions/node/v20.10.0/lib/node_modules/@morten-olsen/mini-loader-cli/node_modules/@trpc/client/dist/httpBatchLink-d0f9eac9.mjs:189:60
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**To Reproduce**

1. Create sample workload based on the guide (say test2.ts):
```ts
import { http } from "@morten-olsen/mini-loader";
import fastify from "fastify";

const server = fastify();

// Handling all requests and returning the requested URL
server.all("*", async (req) => {
  return req.url;
});

// Listening on the path provided by mini loader
server.listen({
  path: http.getPath(),
});

 ```   

2. Run it with auto-imports (or without) `mini-loader loads push -r -ai test2.ts`

**Expected behavior**
Exception with above mentioned message.

**Comment by denissb** [comment]
Got it, I needed to provide an identifier, so 
`mini-loader loads push -ai test2.ts -i second`  works fine.

Probably the guide should be updated.

**Comment by morten-olsen** [comment]
Ah, you are correct - disabled the auto id generation because it quickly became messy, but will re-enable it in #45, but apply a prefix to autogenerated ids

Also created #46 which should allow for easier management of prefixes, such as the auto-id/ prefix
